#!/bin/bash

if +[$EUID -ne 0]
then
	echo "This script must be run as root"
	exit 1
fi
clear
RGEX='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9](1,3)$'
echo -n "Primera direccion de DNS "
read primDNS
echo -n "Sgunda direccion de DNS "
read seguDNS

if [[ $primDNS =~ $REGEX ]] && [[ $seguDNS =~ $REGEX ]]
then
	echo "# Generated by NetworkManager and Oscar Fortea"  > /etc/resolv.conf
	echo "search etpc.edu" >> /etc/resolv.conf
	echo "nameserver $primDNS" >> /etc/resolv.conf
	echo "nameserver $seguDNS" >> /etc/resolv.conf
	echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	
else
	echo "NO TE LA ACEPTO. ME CIERRO"
	exit 1
fi

exit 0
